#!/bin/bash

set -e

# Wait for MySQL to be ready
while ! mysqladmin ping -h"localhost" --silent; do
    sleep 1
done

# Create databases and users dynamically
mysql -u root -p"${MYSQL_ROOT_PASSWORD}" <<EOF
CREATE DATABASE IF NOT EXISTS ${MYSQL_FRONTEND_DATABASE};
CREATE USER IF NOT EXISTS '${MYSQL_FRONTEND_USER}'@'%' IDENTIFIED BY '${MYSQL_FRONTEND_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MYSQL_FRONTEND_DATABASE}.* TO '${MYSQL_FRONTEND_USER}'@'%';

CREATE DATABASE IF NOT EXISTS ${MYSQL_FRONTEND_DATABASE}_test;
CREATE USER IF NOT EXISTS '${MYSQL_FRONTEND_USER}'@'%' IDENTIFIED BY '${MYSQL_FRONTEND_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MYSQL_FRONTEND_DATABASE}_test.* TO '${MYSQL_FRONTEND_USER}'@'%';

CREATE DATABASE IF NOT EXISTS ${MYSQL_QUOTES_DATABASE};
CREATE USER IF NOT EXISTS '${MYSQL_QUOTES_USER}'@'%' IDENTIFIED BY '${MYSQL_QUOTES_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MYSQL_QUOTES_DATABASE}.* TO '${MYSQL_QUOTES_USER}'@'%';
FLUSH PRIVILEGES;

EOF
